services:
  mongodb:
    image: mongo:latest
    container_name: rag-dev-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: rag
    ports:
      - 27017:27017
    volumes:
      - ./script/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: rag-dev-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@rag-dev-mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081